/**
 * Generate a "bootstrap skill" markdown for an AI agent that wants to use this app's API.
 *
 * Design notes (so this can be reused across apps):
 * - Don't list endpoints — they change; tell the agent to read /api/openapi.json instead.
 * - Don't embed the bearer token — it's a separate artifact the user hands over.
 * - Keep it short. The agent's job is to read the schema, this just orients it.
 *
 * To reuse in another newbuild app: copy this file, change the four args passed in
 * by the calling component (appName / description / dataModel / capabilities).
 */
export interface AgentSkillInput {
  /** Lowercase app slug, used as filename and shown in the title (e.g. "invest"). */
  appName: string
  /** Origin of the app, e.g. "https://invest.example.com". */
  baseUrl: string
  /**
   * One paragraph: what the app is for, who uses it.
   * No endpoint names — describe the *purpose*.
   */
  description: string
  /**
   * Short paragraph (or bullet list) describing the data model in plain English —
   * what the resources are and how they relate. Helps the agent map the OpenAPI
   * paths to real concepts.
   */
  dataModel: string
  /**
   * Optional list of "things this agent is typically asked to do" — feeds the
   * agent's planning loop without locking it in to a specific endpoint name.
   */
  capabilities?: string[]
}

export function agentSkill(input: AgentSkillInput): string {
  const { appName, baseUrl, description, dataModel, capabilities = [] } = input
  const base = baseUrl.replace(/\/$/, '')

  const capsBlock = capabilities.length
    ? `\n## Typical tasks\n\n${capabilities.map((c) => `- ${c}`).join('\n')}\n`
    : ''

  return `# ${appName} — agent skill

## What this app is

${description}

${dataModel}

## Authentication

Every request needs an \`Authorization: Bearer <token>\` header. The user has issued
you a long-lived JWT from the app's profile page; treat it as a secret, store it
outside this file, and never log or echo it.

If you get **401**, your token is missing, malformed, or expired — stop and ask the
user for a fresh one rather than retrying. If you get **403** with a body other than
a generic auth error, the token is fine but the action is forbidden for this user.

## Discovering endpoints

**Do not guess endpoint paths.** Read the schema before calling anything new.

- Machine-readable OpenAPI 3.x schema:
  \`GET ${base}/api/openapi.json\`
- Human-readable Swagger UI (browse this if you're unsure):
  \`${base}/api/agent\`

Workflow on a fresh task:
1. \`GET ${base}/api/openapi.json\` once at session start, cache the result.
2. Search the \`paths\` object for endpoints relevant to the task (by tag, path
   keyword, or HTTP method). The schema includes request/response shapes —
   match your payload to those exactly.
3. If a request returns **422**, re-read the schema for that path. The error
   body lists the failing fields; line them up with the schema and retry.
4. The full base for every API call is \`${base}/api/...\`.

## Idiomatic behavior

- **Idempotency where it exists:** prefer bulk/upsert endpoints (their docstrings
  in the schema mark them idempotent) over many sequential single creates when
  you're backfilling data.
- **One user, one watchlist:** every resource is scoped to the authenticated user.
  You cannot reach another user's data, so don't try.
- **Don't write what the user writes:** anything labeled "user-authored" in the
  data model description is for the human to edit in the UI; agents append to
  versioned/AI-authored siblings instead. Inspect field names and the path's
  description in the schema if you're unsure.
- **Follow the rate limits implied by the cron schedule:** if you're scheduled
  daily, don't poll hourly without a reason. If you're scheduled hourly, don't
  burst hundreds of requests in seconds.

## Failure modes that aren't bugs

| Status | Meaning | What to do |
|---|---|---|
| 401 | Bad/missing/expired token | Stop, request a new token from the user |
| 403 | Authenticated but action forbidden | Read the response body; do not retry |
| 404 | Resource not found or not yours | Don't retry; the ID may be stale |
| 409 | Conflict (usually a unique-key collision) | Treat as success-equivalent if your goal was idempotent insert |
| 422 | Payload doesn't match schema | Re-read the schema, fix the body, retry once |
| 5xx | Server error | Backoff and retry with jitter; alert if persistent |
${capsBlock}
---

*This file is generated by the app at \`${base}\`. The endpoint list is
intentionally not pinned here — read \`/api/openapi.json\` for that.*
`
}

/**
 * Trigger a browser download of the given markdown content as a file named
 * \`<appName>-agent.md\`.
 */
export function downloadSkill(appName: string, markdown: string) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${appName}-agent.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
